### ISSUE TITLE
Fazer a integração da Página com os Resultados

### ISSUE THREAD

**Issue by nadiabarbosa** [RushiamX/Projeto-Light#20]
Após o usuário preencher o formulário principal e clicar no botão de realizar o calculo
este será encaminhado para uma outra pagina que mostrará o resultado:

- Potência necessária;

- Perdas estimadas;

- Opções para escolher o equipamento;

- Valor do investimento;

- Botão para novo cálculo (link para a tela do formulário de cálculo);

- Compartilhar com o Cliente;

**Comment by RushiamX** [comment]
A integração foi realizada
